### ISSUE TITLE
`trace`-level logs should not include the stack of the `consola` module itself

### ISSUE THREAD

**Issue by trevor-vaughan** [unjs/consola#214]
### Environment

All

### Reproduction

Run a log at the `trace` level and the following output results:

```
at FancyReporter.formatLogObj (node_modules/consola/dist/shared/consola.4bbae468.cjs:597:20)
at FancyReporter.log (node_modules/consola/dist/shared/consola.deac7d5a.cjs:53:23)
at Consola._log (node_modules/consola/dist/core.cjs:383:16)
at resolveLog (node_modules/consola/dist/core.cjs:351:14)
at Consola._logFn (node_modules/consola/dist/core.cjs:379:5)
at node_modules/consola/dist/core.cjs:308:19 
<actual application trace>
```

### Describe the bug

A trace from the application should not end up with noise from the logging library.

### Additional context

In theory, you could reject all lines that start with `node_modules/consola` from the trace.

**Comment by trevor-vaughan** [comment]
Relates to #194
