### ISSUE TITLE
Unable to build Nuxt 2 projects

### ISSUE THREAD

**Issue by Henk0** [unjs/consola#329]
### Environment

Nuxt 2 project Node 20 and 18

### Reproduction

Try to build new nuxt 2 project

### Describe the bug

I believe you messed up require cjs path
<img width="701" alt="Снимок экрана 2024-12-26 в 18 22 53" src="https://github.com/user-attachments/assets/91d63977-6aa9-4fe9-b53e-e64b77fd42a0" />

### Additional context

<img width="618" alt="Снимок экрана 2024-12-26 в 18 28 03" src="https://github.com/user-attachments/assets/67f577f6-aeb1-4b54-ab2a-d137b4d6f7c9" />

**Comment by Ashiksmart** [comment]
I am also facing the same error while trying to run the build or start the Nuxt 2 projects. It throws an error like this:


.../node_modules/@nuxt/config/dist/config.js:514
      consola.warn("`mode` option is deprecated. You can safely remove it from `nuxt.config`");
              ^

TypeError: consola.warn is not a function
    at Object.getNuxtConfig (/home/mohammed/Ashik/Repositories/comed-ee-standportal/node_modules/@nuxt/config/dist/config.js:514:15)
    at new Nuxt (/home/mohammed/Ashik/Repositories/comed-ee-standportal/node_modules/@nuxt/core/dist/core.js:287:27)
    at start (/home/mohammed/Ashik/Repositories/comed-ee-standportal/server/index.js:14:16)
    at Object.<anonymous> (/home/mohammed/Ashik/Repositories/comed-ee-standportal/server/index.js:43:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
[nodemon] app crashed - waiting for file changes before starting...

**Comment by pi0** [comment]
Change temporarily reverted in [v3.3.3](https://github.com/unjs/consola/releases/tag/v3.3.3)
